### ISSUE TITLE
Example code error in wireless_profile.py

### ISSUE THREAD

**Issue by bsmeding** [cisco-en-programmability/dnacenter-ansible#71] opened 2022-08-03 05:55 UTC
**Prerequisites**
* [Y] Have you tested the operation in the API directly?
* [Y] Do you have the latest Ansible collection version?

**Describe the bug**
Naming of variable wrong in : [dnacenter-ansible](https://github.com/cisco-en-programmability/dnacenter-ansible)/[plugins](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main/plugins)/[modules](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main/plugins/modules)/wireless_profile.py

It stated in whe example that the Wireless profile name must be given under profileDetails, only then an arror raise
`"state is present but any of the following are missing: wirelessProfileName"}`

```
- name: Create
  cisco.dnac.wireless_profile:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    state: present
    profileDetails:
      name: string
      sites:
      - string
      ssidDetails:
      - enableFabric: true
        flexConnect:
          enableFlexConnect: true
          localToVlan: 0
        interfaceName: string
        name: string
        type: string
```

**Expected behavior**
Accept input of example

**Screenshots**
N/A (in  environment cannot make screenshots)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 2.2.3.6
* Ansible Version: 2.10
* Collection version:  3.3.1
* OS Version: rhel 7.9

**Additional context**

when changing to this code listed below it works, but the naming is not consistent then with the output of `[wireless_profile_info.py](https://github.com/cisco-en-programmability/dnacenter-ansible/blob/main/plugins/modules/wireless_profile_info.py)` because the output give the correct tree as in the example above (profileDetails -> name).

```
- name: Create
  cisco.dnac.wireless_profile:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    state: present
    wirelessProfileName: string
    profileDetails:
      sites:
      - string
      ssidDetails:
      - enableFabric: true
        flexConnect:
          enableFlexConnect: true
          localToVlan: 0
        interfaceName: string
        name: string
        type: string
```

**Comment by bvargasre** [comment] 2022-08-12 21:06
Hi @bsmeding , thanks for reporting the bug, the new dnacenter-ansible version v6.5.3 is expected to fix this error.

**Comment by bsmeding** [comment] 2022-08-12 21:37
Hi @bvargasre thanks for the quick fix!

**Comment by bvargasre** [comment] 2022-08-12 21:58
If the problem is solved feel free to close the issue, if the problem persists or a new one arises let me know and I will gladly help you.

**Closed** 2022-08-25 15:29 UTC
Labels: in-progress

**Comment by bsmeding** [comment] 2022-08-25 16:52
Thanks. Didn't had any time for new version install on ou environment. Will test soon
